In [53]:
!python --version

Python 3.13.9


In [54]:
import numpy as np
from numpy.linalg import inv

In [55]:
n1 = np.array([[22, 33, 44]])

# Addition of n1 and v1
v1 = np.array([[2, 2, 2]])
add = n1 + v1
print('n1 + v1 :- ', add)

# Subtraction of n1 and v2
v2 = np.array([[2, 3, 4]])
sub = n1 - v2
print('n1 - v2 :- ', sub)

# Sclaer Multiplication of n1 with 25
mul = n1 * 25
print('Scaler Multi. of n1 * 25 :- ', mul)

# Element wise Multiplication
a = np.array([11, 12, 13])
print('Element wise Multi. n1 x a :- ', np.multiply(n1,a))

# Vector Multiplication of n1
re = n1.reshape(3,1)
b = np.full((1, 4), 3)
print('Vector Multi. of re x b :- \n', np.multiply(re, b))

# Multi. of n1 and n1^T 
trans = n1.T
print('Multi. of n1 & n1^T :- \n', np.dot(n1,trans))
# Alternative of np.dot is "a @ b"

# Vector multi. of v1 ((3x3) Prime no.) and inverse of n1
v1 = np.array([[2, 3, 5], 
              [7, 11, 13], 
              [17, 19, 23]])
v2 = inv(v1)
out = v1 @ v2
print('Vector multi. of v1 ((3x3) Prime no.) and inverse of v1 :- \n' ,np.round(out, decimals=1))

# Univeral Functions in Numpy:-

# 1.) Trignometric ufunc :-

print('Sin angles for v1 :- \n', np.sin(v1)) # Gives sin angles acc. to elements 

# 2.) Arithmetic ufunc :-

q = np.array([7, 8, 9])

print('Sum of v1 & q :- \n', np.add(v1, q)) # Add p & q

# 3.) Comparision ufunc :-

print('Comparision func. v1 > q :- \n', np.greater(v1, q))
print('Comparision func. v1 = q :- \n', np.equal(v1, q))
print('Comparision func. v1 != q :- \n', np.not_equal(v1, q))


n1 + v1 :-  [[24 35 46]]
n1 - v2 :-  [[20 30 40]]
Scaler Multi. of n1 * 25 :-  [[ 550  825 1100]]
Element wise Multi. n1 x a :-  [[242 396 572]]
Vector Multi. of re x b :- 
 [[ 66  66  66  66]
 [ 99  99  99  99]
 [132 132 132 132]]
Multi. of n1 & n1^T :- 
 [[3509]]
Vector multi. of v1 ((3x3) Prime no.) and inverse of v1 :- 
 [[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
Sin angles for v1 :- 
 [[ 0.90929743  0.14112001 -0.95892427]
 [ 0.6569866  -0.99999021  0.42016704]
 [-0.96139749  0.14987721 -0.8462204 ]]
Sum of v1 & q :- 
 [[ 9 11 14]
 [14 19 22]
 [24 27 32]]
Comparision func. v1 > q :- 
 [[False False False]
 [False  True  True]
 [ True  True  True]]
Comparision func. v1 = q :- 
 [[False False False]
 [ True False False]
 [False False False]]
Comparision func. v1 != q :- 
 [[ True  True  True]
 [False  True  True]
 [ True  True  True]]
